### ISSUE TITLE
Crashing when hitting an entity [1.0.8]

### ISSUE THREAD

**Issue by platinumphoenix2** [Mixac1/DangerRPG#17]
> ---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 10/2/16 1:48 PM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at mixac1.dangerrpg.api.item.IADynamic.getRaw(IADynamic.java:27)
	at mixac1.dangerrpg.api.item.ItemAttribute.get(ItemAttribute.java:39)
	at mixac1.dangerrpg.capability.ia.IALevel.isMax(IALevel.java:22)
	at mixac1.dangerrpg.capability.RPGableItem.upEquipment(RPGableItem.java:358)
	at mixac1.dangerrpg.event.EventHandlerItem.onDealtDamage(EventHandlerItem.java:106)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_228_EventHandlerItem_onDealtDamage_DealtDamageEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at mixac1.dangerrpg.hook.HookEntities.attackTargetEntityWithCurrentItem(HookEntities.java:106)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java)
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:821)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mixac1.dangerrpg.api.item.IADynamic.getRaw(IADynamic.java:27)
	at mixac1.dangerrpg.api.item.ItemAttribute.get(ItemAttribute.java:39)
	at mixac1.dangerrpg.capability.ia.IALevel.isMax(IALevel.java:22)
	at mixac1.dangerrpg.capability.RPGableItem.upEquipment(RPGableItem.java:358)
	at mixac1.dangerrpg.event.EventHandlerItem.onDealtDamage(EventHandlerItem.java:106)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_228_EventHandlerItem_onDealtDamage_DealtDamageEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at mixac1.dangerrpg.hook.HookEntities.attackTargetEntityWithCurrentItem(HookEntities.java:106)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java)
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:821)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@5daffc56
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 282561656 bytes (269 MB) / 716943360 bytes (683 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_D6 43 mods loaded, 43 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	FastCraft{1.23} [FastCraft] (fastcraft-1.23.jar) 
	UCHIJAAAA	debug{1.0} [debug] (denseores-1.6.2.jar) 
	UCHIJAAAA	TakumiMod{1.6.1-1.7.10} [?Craft [ Takumi Craft ]] ([1.7.10]TakumiCraft-1.6.1.jar) 
	UCHIJAAAA	advancedcapes{1.5} [Advanced Capes] (advancedcapes-1.5.jar) 
	UCHIJAAAA	gibby_dungeons{1.7} [Arcana RPG] (Arcana RPG 1.6.1 - 1.7.10.jar) 
	UCHIJAAAA	BrandonsCore{1.0.0.12} [Brandon's Core] (BrandonsCore-1.0.0.12.jar) 
	UCHIJAAAA	speedytoolsmod{2.1.0} [Build Faster Mod] (BuildFaster-2-1-0-Minecraft1-7-10.zip) 
	UCHIJAAAA	cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (cfm-3.4.8-mc1.7.10.jar) 
	UCHIJAAAA	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.0.jar) 
	UCHIJAAAA	craftguide{1.6.8.2} [CraftGuide] (CraftGuide-1.6.8.2-forge.jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(21feb16).jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCHIJAAAA	dangerrpg{1.0.8} [DangerRPG] (DangerRPG-1.7.10-1.0.8.jar) 
	UCHIJAAAA	Dollars{1.0.0} [Dollars] (Dollars.zip) 
	UCHIJAAAA	dldungeonsjdg{1.8.13} [Doomlike Dungeons] (DoomlikeDungeons-1.8.13-MC1.7.10.jar) 
	UCHIJAAAA	DraconicEvolution{1.0.2h} [Draconic Evolution] (Draconic-Evolution-1.7.10-1.0.2h.jar) 
	UCHIJAAAA	eggcraft{1.0.2} [Egg Craft] (EggCraft_1.7.10_(1.0.2).jar) 
	UCHIJAAAA	ElementalItems{4.0.0} [Elemental Items mod] (Elemental-Items-Mod-1.7.10.zip) 
	UCHIJAAAA	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJAAAA	FairyFactions{0.5.2a} [Fairy Factions] (fairy-factions-1.7-0.5.2a.jar) 
	UCHIJAAAA	FinderCompass{1.7.10c} [Finder Compass] (FinderCompass-1.7.10.jar) 
	UCHIJAAAA	ganyssurface{1.12.8} [Gany's Surface] (Ganys Surface-1.12.8.jar) 
	UCHIJAAAA	howlingmoon{1.1.1} [Howling Moon] (howlingMoon-1.7.10-1.1.1.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	ironbackpacks{1.7.10-1.2.15} [Iron Backpacks] (Iron-Backpacks-Mod-1.7.10.jar) 
	UCHIJAAAA	me{1.3.1.2} [More Enchantments] (More-Enchantments-Mod-1.7.10.jar) 
	UCHIJAAAA	AencEx{0.0.1} [AencEx] (More-Enchantments-Mod-1.7.10.jar) 
	UCHIJAAAA	MoreFurnaces{1.3.7} [More Furnaces] (MoreFurnaces-1.3.7-MC1.7.2.jar) 
	UCHIJAAAA	recipehandler{1.7.10} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.3(1.7.10).jar) 
	UCHIJAAAA	OpenMods{0.9.1} [OpenMods] (OpenModsLib-1.7.10-0.9.1.jar) 
	UCHIJAAAA	OpenBlocks{1.5.1} [OpenBlocks] (OpenBlocks-1.7.10-1.5.1.jar) 
	UCHIJAAAA	OreSpawn{1.7.10.20.3} [OreSpawn] (orespawn-1.7.10-20.3.zip) 
	UCHIJAAAA	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) 
	UCHIJAAAA	Roguelike{1.5.0} [Roguelike Dungeons] (roguelike-1.7.10-1.5.0b.jar) 
	UCHIJAAAA	AS_Ruins{15.4} [Ruins Spawning System] (Ruins-1.7.10.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	wawla{1.3.3} [What Are We Looking At] (Wawla-1.3.3-1.7.10.jar) 
	UCHIJAAAA	denseores{1.0} [Dense Ores] (denseores-1.6.2.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	Stencil buffer state: Function set: GL30, pool: disabled, bits: 0
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 3 / 8; [EntityPlayerMP['alvaro'/984, l='take him out', x=372.37, y=76.00, z=274.35], EntityPlayerMP['Marco'/8343, l='take him out', x=54.97, y=20.00, z=154.70], EntityPlayerMP['Leonel'/21584, l='take him out', x=-17.51, y=46.00, z=155.29]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.7.10_HD_U_D6
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 4.5.13447 Compatibility Profile Context 20.19.0.32837
	OpenGlRenderer: AMD Radeon R7 200 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

_________________________________________________________________________________________
# Another crash report

> ---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 10/2/16 1:25 PM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at mixac1.dangerrpg.api.item.IADynamic.getRaw(IADynamic.java:27)
	at mixac1.dangerrpg.api.item.ItemAttribute.get(ItemAttribute.java:39)
	at mixac1.dangerrpg.capability.ia.IALevel.isMax(IALevel.java:22)
	at mixac1.dangerrpg.capability.RPGableItem.upEquipment(RPGableItem.java:358)
	at mixac1.dangerrpg.event.EventHandlerItem.onDealtDamage(EventHandlerItem.java:106)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_228_EventHandlerItem_onDealtDamage_DealtDamageEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at mixac1.dangerrpg.hook.HookEntities.attackTargetEntityWithCurrentItem(HookEntities.java:106)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java)
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:821)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mixac1.dangerrpg.api.item.IADynamic.getRaw(IADynamic.java:27)
	at mixac1.dangerrpg.api.item.ItemAttribute.get(ItemAttribute.java:39)
	at mixac1.dangerrpg.capability.ia.IALevel.isMax(IALevel.java:22)
	at mixac1.dangerrpg.capability.RPGableItem.upEquipment(RPGableItem.java:358)
	at mixac1.dangerrpg.event.EventHandlerItem.onDealtDamage(EventHandlerItem.java:106)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_228_EventHandlerItem_onDealtDamage_DealtDamageEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at mixac1.dangerrpg.hook.HookEntities.attackTargetEntityWithCurrentItem(HookEntities.java:106)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java)
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:821)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@3c89695d
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 281901520 bytes (268 MB) / 781148160 bytes (744 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_D6 43 mods loaded, 43 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	FastCraft{1.23} [FastCraft] (fastcraft-1.23.jar) 
	UCHIJAAAA	debug{1.0} [debug] (denseores-1.6.2.jar) 
	UCHIJAAAA	TakumiMod{1.6.1-1.7.10} [?Craft [ Takumi Craft ]] ([1.7.10]TakumiCraft-1.6.1.jar) 
	UCHIJAAAA	advancedcapes{1.5} [Advanced Capes] (advancedcapes-1.5.jar) 
	UCHIJAAAA	gibby_dungeons{1.7} [Arcana RPG] (Arcana RPG 1.6.1 - 1.7.10.jar) 
	UCHIJAAAA	BrandonsCore{1.0.0.12} [Brandon's Core] (BrandonsCore-1.0.0.12.jar) 
	UCHIJAAAA	speedytoolsmod{2.1.0} [Build Faster Mod] (BuildFaster-2-1-0-Minecraft1-7-10.zip) 
	UCHIJAAAA	cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (cfm-3.4.8-mc1.7.10.jar) 
	UCHIJAAAA	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.0.jar) 
	UCHIJAAAA	craftguide{1.6.8.2} [CraftGuide] (CraftGuide-1.6.8.2-forge.jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(21feb16).jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCHIJAAAA	dangerrpg{1.0.8} [DangerRPG] (DangerRPG-1.7.10-1.0.8.jar) 
	UCHIJAAAA	Dollars{1.0.0} [Dollars] (Dollars.zip) 
	UCHIJAAAA	dldungeonsjdg{1.8.13} [Doomlike Dungeons] (DoomlikeDungeons-1.8.13-MC1.7.10.jar) 
	UCHIJAAAA	DraconicEvolution{1.0.2h} [Draconic Evolution] (Draconic-Evolution-1.7.10-1.0.2h.jar) 
	UCHIJAAAA	eggcraft{1.0.2} [Egg Craft] (EggCraft_1.7.10_(1.0.2).jar) 
	UCHIJAAAA	ElementalItems{4.0.0} [Elemental Items mod] (Elemental-Items-Mod-1.7.10.zip) 
	UCHIJAAAA	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJAAAA	FairyFactions{0.5.2a} [Fairy Factions] (fairy-factions-1.7-0.5.2a.jar) 
	UCHIJAAAA	FinderCompass{1.7.10c} [Finder Compass] (FinderCompass-1.7.10.jar) 
	UCHIJAAAA	ganyssurface{1.12.8} [Gany's Surface] (Ganys Surface-1.12.8.jar) 
	UCHIJAAAA	howlingmoon{1.1.1} [Howling Moon] (howlingMoon-1.7.10-1.1.1.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	ironbackpacks{1.7.10-1.2.15} [Iron Backpacks] (Iron-Backpacks-Mod-1.7.10.jar) 
	UCHIJAAAA	me{1.3.1.2} [More Enchantments] (More-Enchantments-Mod-1.7.10.jar) 
	UCHIJAAAA	AencEx{0.0.1} [AencEx] (More-Enchantments-Mod-1.7.10.jar) 
	UCHIJAAAA	MoreFurnaces{1.3.7} [More Furnaces] (MoreFurnaces-1.3.7-MC1.7.2.jar) 
	UCHIJAAAA	recipehandler{1.7.10} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.3(1.7.10).jar) 
	UCHIJAAAA	OpenMods{0.9.1} [OpenMods] (OpenModsLib-1.7.10-0.9.1.jar) 
	UCHIJAAAA	OpenBlocks{1.5.1} [OpenBlocks] (OpenBlocks-1.7.10-1.5.1.jar) 
	UCHIJAAAA	OreSpawn{1.7.10.20.3} [OreSpawn] (orespawn-1.7.10-20.3.zip) 
	UCHIJAAAA	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) 
	UCHIJAAAA	Roguelike{1.5.0} [Roguelike Dungeons] (roguelike-1.7.10-1.5.0b.jar) 
	UCHIJAAAA	AS_Ruins{15.4} [Ruins Spawning System] (Ruins-1.7.10.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	wawla{1.3.3} [What Are We Looking At] (Wawla-1.3.3-1.7.10.jar) 
	UCHIJAAAA	denseores{1.0} [Dense Ores] (denseores-1.6.2.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	Stencil buffer state: Function set: GL30, pool: disabled, bits: 0
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 3 / 8; [EntityPlayerMP['Leonel'/26623, l='take him out', x=14.70, y=52.00, z=169.70], EntityPlayerMP['Marco'/105698, l='take him out', x=-177.32, y=70.00, z=316.20], EntityPlayerMP['alvaro'/1313, l='take him out', x=-106.54, y=68.00, z=192.00]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.7.10_HD_U_D6
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 4.5.13447 Compatibility Profile Context 20.19.0.32837
	OpenGlRenderer: AMD Radeon R7 200 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by Mixac1** [comment]
I need information about your equipment at that moment. Are all equipment items RPGable (with level)?

**Comment by platinumphoenix2** [comment]
I was wearing an Iron Chest Plate and Iron Leggings, my tool was an Iron Sword.
I only applied 1 level to my health - the items did not have anything special.
(I got in again and hit the mob with an empty hand and still crashed).
Config options were set to default.

**Comment by Mixac1** [comment]
What? Your sword was without "level 1", but config options were set to default, wasn't it?

**Comment by platinumphoenix2** [comment]
Sorry, I didn't know that the swords received levels on their own.
I started multiple worlds with different items, but the crash remained persistent.
In the current world, I am holding a level 3 diamond sword + Iron Helmet + Iron Chestplate + Chain Leggings + Chain Boots (each piece of armor is level 1).
Again, upon hitting an entity, I crash - even if it's just with a bare hand.

Yesterday, I played in a world and the crash happened again, but, **only** when wearing Iron armor.
After removing my Iron armor from the aforementioned world, the crash no longer occurred.
I will test with the rest of vanilla armor and see if the issue occurs.

**Comment by Mixac1** [comment]
Ok, I will try fix it in next version.

**Comment by Mixac1** [comment]
I have just tried fix it.
Could you check it in new version?

**Comment by platinumphoenix2** [comment]
The game crashes upon start up

> cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
	at mixac1.dangerrpg.item.gem.Gem.addItemTypes(Gem.java:48)
	at mixac1.dangerrpg.init.RPGGems.load(RPGGems.java:29)
	at mixac1.dangerrpg.proxy.CommonProxy.preInit(CommonProxy.java:38)
	at mixac1.dangerrpg.proxy.ClientProxy.preInit(ClientProxy.java:27)
	at mixac1.dangerrpg.DangerRPG.preInit(DangerRPG.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 10 more
Caused by: java.lang.ClassNotFoundException: scala.actors.threadpool.Arrays
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 42 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 44 more

**Comment by Mixac1** [comment]
Is the bug appear?

**Comment by platinumphoenix2** [comment]
Issue fixed.
